version: '3.7'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      ADMINER_DEFAULT_DB: postgres
      ADMINER_LOGIN: postgres
      ADMINER_PASSWORD: your_password

volumes:
  postgresql-data:
